
db:
  SQLALCHEMY_DATABASE_URI: mariadb+mariadbconnector://forecastapp:password456@172.0.0.1:3306/SALES

frontend:
  STATIC_FOLDER: ../../frontend-react/build

metabase:
  METABASE_SITE_URL: http://localhost:3001
  METABASE_SECRET_KEY:
  METABASE_DASHBOARD_NO: 5
