global:
  scrape_interval: 10s

  external_labels:
    monitor: "flask-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "flask_app"
    static_configs:
      - targets: ["host.docker.internal:5000"]
